global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    dns_sd_configs:
      - names:
          - 'tasks.cadvisor'
        type: 'A'
        port: 8080

  - job_name: 'docker-nodes'
    # Scrapes Docker daemon metrics (requires metrics-addr in daemon.json)
    static_configs:
      - targets: ['172.16.7.42:9323', '172.16.7.111:9323']
